targets:
  $default:
    builders:
      json_serializable:
        options:
#          explicit_to_json: true
#          field_rename: snake_case
#          checked: true
#          disallow_unrecognized_keys: false
#          any_map: false
          
      freezed:
        options:
          union_key: type
          union_value_case: snake
